"""Drawn-schedule detection, and the refusals that are the point of it.

This phase was held back once because a naive detector fabricated tables out
of member outlines and bolt gauge lines. So the negative tests here are not
edge cases -- they are the specification. A missing schedule is acceptable; a
fabricated engineering schedule is not, because it reads as tabulated fact and
nobody re-derives it from the sheet.

Two fixtures, both real code paths:

* `SSD11-member-schedule.dxf` -- generated by `scripts/make_schedule_fixture.py`
  (see its docstring for the licensing decision), containing one genuine
  schedule *and* every false-positive grid from the real drawing.
* `SSD09.0-02.dxf` -- the real sheet. It has no schedule, and the detector
  must say so.
"""

from __future__ import annotations

import asyncio
from pathlib import Path

import pytest

from src.ingestion.cad.dxf_reader import DxfReader
from src.ingestion.cad.models import CadDocument, CadGeometry, CadTextEntity, LayoutSheet
from src.ingestion.cad.schedules import (
    detect_schedules,
    schedule_markdown,
    schedule_row_sentences,
)
from src.ingestion.loaders.base import BoundingBox
from src.ingestion.loaders.dxf_loader import DxfLoader

pytest.importorskip("ezdxf")

FIXTURES = Path(__file__).parents[4] / "tests" / "fixtures" / "cad"
SCHEDULE = FIXTURES / "SSD11-member-schedule.dxf"
DETAIL = FIXTURES / "SSD09.0-02.dxf"

pytestmark = pytest.mark.skipif(
    not SCHEDULE.exists() or not DETAIL.exists(), reason="CAD fixtures not present"
)


@pytest.fixture(scope="module")
def schedule_report():
    return detect_schedules(DxfReader().read(SCHEDULE))


@pytest.fixture(scope="module")
def detail_report():
    return detect_schedules(DxfReader().read(DETAIL))


@pytest.fixture(scope="module")
def schedule(schedule_report):
    assert schedule_report.schedules, "the fixture's schedule was not detected"
    return schedule_report.schedules[0]


# Hand-built drawings, for the scoring rules themselves.


def line(entity_id: str, points, layer: str = "S-SCHEDULE") -> CadGeometry:
    return CadGeometry(
        entity_id=entity_id,
        entity_type="LINE",
        layer=layer,
        layout_index=0,
        points=tuple(points),
    )


def text(body: str, x: float, y: float, height: float = 1.5) -> CadTextEntity:
    width = max(len(body), 1) * height * 0.6
    return CadTextEntity(
        text=body,
        layer="S-TEXT",
        layout_index=0,
        bbox=BoundingBox(x0=x, y0=y, x1=x + width, y1=y + height, space="model"),
        height=height,
    )


def grid_drawing(
    rows: int, columns: int, cell_text: bool = True, layer: str = "S-SCHEDULE"
) -> CadDocument:
    """A `rows` x `columns` grid, optionally with a value in every cell."""
    width, height = 20.0, 6.0
    xs = [i * width for i in range(columns + 1)]
    ys = [i * height for i in range(rows + 1)]
    geometry = [line(f"H{i}", [(xs[0], y), (xs[-1], y)], layer) for i, y in enumerate(ys)]
    geometry += [line(f"V{i}", [(x, ys[0]), (x, ys[-1])], layer) for i, x in enumerate(xs)]

    texts = []
    if cell_text:
        for r in range(rows):
            for c in range(columns):
                texts.append(text(f"R{r}C{c}", xs[c] + 1.0, ys[r] + 2.0))
    return CadDocument(
        layouts=[LayoutSheet(name="Model", index=0, is_model_space=True)],
        geometry=geometry,
        texts=texts,
    )


class TestTheRealSchedule:
    """§14 -- the fixture must produce TABLE_DETECTED with the right values."""

    def test_exactly_one_schedule_is_found(self, schedule_report):
        """Not two. The fixture also contains five decoy grids."""
        assert len(schedule_report.schedules) == 1

    def test_the_title_is_read_from_the_heading_above_the_grid(self, schedule):
        assert schedule.title == "MEMBER SCHEDULE"

    def test_the_shape_is_right(self, schedule):
        assert schedule.column_count == 6
        assert schedule.row_count == 5, "one header row plus four data rows"
        assert len(schedule.data_rows()) == 4

    def test_the_headers_are_the_first_row(self, schedule):
        assert schedule.columns == (
            "MARK",
            "DESCRIPTION",
            "DWG.NO",
            "QTY",
            "WT. (KG)",
            "REMARKS",
        )

    def test_every_data_row_is_read_correctly(self, schedule):
        assert schedule.data_rows() == [
            ["CE-4", "ASTM A36 W12X40", "S-201", "1", "245", "COLUMN"],
            ["BP-1", "ASTM A36 25MM THK MS PLATE", "S-202", "1", "38", "GROUT 25MM"],
            ["AB-2", "ASTM A36 ANGLE BAR L75X75X6", "S-203", "4", "12", ""],
            ["HB-1", "ASTM A325 BOLTS 20MM DIA", "S-204", "16", "2", "HSFG"],
        ]

    def test_an_empty_cell_stays_empty(self, schedule):
        """AB-2 has no remark. Inventing one, or shifting the row left to
        close the gap, would corrupt every column after it."""
        row = schedule.data_rows()[2]
        assert row[0] == "AB-2"
        assert row[5] == ""

    def test_cells_know_their_row_and_column(self, schedule):
        bp1 = next(c for c in schedule.cells if c.text == "BP-1")
        qty = next(c for c in schedule.cells if c.row == bp1.row and c.column == 3)
        assert qty.text == "1", "the quantity of BP-1, by position not by guess"

    def test_cells_carry_their_own_coordinates(self, schedule):
        """§12 -- a cell has to be locatable for a UI to highlight it."""
        for cell in schedule.cells:
            assert cell.bbox is not None
            assert cell.bbox.space == "model"
            assert cell.bbox.x1 > cell.bbox.x0

    def test_the_schedule_records_its_source(self, schedule):
        assert schedule.layers == ("S-SCHEDULE",)
        assert schedule.source_entity_ids, "no grid-line handles recorded"
        assert schedule.bbox is not None

    def test_confidence_is_high_for_a_genuine_schedule(self, schedule):
        assert schedule.confidence > 0.8, schedule.evidence

    def test_the_evidence_states_why(self, schedule):
        assert "cells hold text" in schedule.evidence
        assert "structural" in schedule.evidence


class TestTheKnownFalsePositives:
    """§4 and §13 -- every grid that defeated the naive detector."""

    def test_the_real_detail_sheet_yields_no_schedule(self, detail_report):
        """SSD09.0-02 has no schedule. Finding one would be the failure this
        whole design exists to prevent."""
        assert detail_report.schedules == []
        assert detail_report.detected is False

    def test_every_rejection_records_a_reason(self, detail_report):
        assert detail_report.rejected
        for name, why in detail_report.rejected:
            assert name and why

    def test_bolt_gauge_lines_are_rejected_for_having_no_content(self, detail_report):
        """The case that settles the design. Five evenly spaced horizontals
        crossed by four verticals *is* a grid; what it is not is a table,
        because nothing sits in its cells."""
        centreline = [why for name, why in detail_report.rejected if "S-CENTERLINE" in name]
        assert centreline, "the bolt gauge was never even considered"
        assert any("no text" in why for why in centreline)

    @pytest.mark.parametrize("layer", ["S-SECT_STEEL", "S-ARROW_HEAD", "S-LEADER", "S-BOLTS"])
    def test_the_other_grid_shaped_layers_are_rejected(self, detail_report, layer):
        assert any(layer in name for name, _ in detail_report.rejected)

    def test_the_decoys_in_the_schedule_fixture_are_rejected_too(self, schedule_report):
        """The positive fixture is also a negative test: the same file holds a
        real schedule and five things that look like one."""
        rejected = " ".join(f"{n} {w}" for n, w in schedule_report.rejected)
        assert "S-CENTERLINE" in rejected
        assert "no text" in rejected


class TestBothKindsOfEvidenceAreRequired:
    """§3 and §8 -- neither half may carry the other."""

    def test_a_perfect_grid_with_no_text_is_not_a_table(self):
        report = detect_schedules(grid_drawing(rows=5, columns=4, cell_text=False))
        assert report.schedules == []
        assert any("no text" in why for _, why in report.rejected)

    def test_the_same_grid_with_text_is_a_table(self):
        """The control for the test above: only the content differs."""
        report = detect_schedules(grid_drawing(rows=5, columns=4, cell_text=True))
        assert len(report.schedules) == 1

    def test_text_with_no_grid_is_not_a_table(self):
        """Aligned text alone is a list, a legend or a column of notes."""
        cad = CadDocument(
            layouts=[LayoutSheet(name="Model", index=0, is_model_space=True)],
            texts=[text(f"ROW {i}", 0.0, i * 6.0) for i in range(5)],
        )
        assert detect_schedules(cad).schedules == []

    def test_a_bare_rectangle_with_text_is_not_a_table(self):
        """A review box has a boundary and content and no rows or columns.
        The closest call in the set."""
        cad = CadDocument(
            layouts=[LayoutSheet(name="Model", index=0, is_model_space=True)],
            geometry=[
                line("H0", [(0.0, 0.0), (40.0, 0.0)], "REVIEW_TEXT_BOX"),
                line("H1", [(0.0, 12.0), (40.0, 12.0)], "REVIEW_TEXT_BOX"),
                line("V0", [(0.0, 0.0), (0.0, 12.0)], "REVIEW_TEXT_BOX"),
                line("V1", [(40.0, 0.0), (40.0, 12.0)], "REVIEW_TEXT_BOX"),
            ],
            texts=[text("FOR REVIEW ONLY", 2.0, 5.0)],
        )
        assert detect_schedules(cad).schedules == []

    def test_a_single_column_of_text_is_not_a_schedule(self):
        report = detect_schedules(grid_drawing(rows=5, columns=1, cell_text=True))
        assert report.schedules == []

    def test_a_grid_with_one_populated_row_is_not_a_schedule(self):
        """A header with nothing under it tabulates nothing."""
        cad = grid_drawing(rows=4, columns=3, cell_text=False)
        cad.texts = [text(f"H{c}", c * 20.0 + 1.0, 20.0) for c in range(3)]
        report = detect_schedules(cad)
        assert report.schedules == []
        assert any("row" in why for _, why in report.rejected)


class TestStructuralFilters:
    def test_lines_that_do_not_span_the_table_are_not_separators(self):
        """A member outline's internal lines stop at a flange rather than
        crossing the section, which is what rejects it structurally."""
        cad = grid_drawing(rows=4, columns=3, cell_text=True)
        # Replace the interior verticals with stubs covering a third of the height.
        cad.geometry = [g for g in cad.geometry if not g.entity_id.startswith("V")]
        cad.geometry += [
            line("V0", [(0.0, 0.0), (0.0, 24.0)]),
            line("V3", [(60.0, 0.0), (60.0, 24.0)]),
            line("Vs", [(20.0, 0.0), (20.0, 8.0)]),
        ]
        report = detect_schedules(cad)
        assert report.schedules == []
        assert any("full-height" in why for _, why in report.rejected)

    def test_two_schedules_on_one_sheet_stay_separate(self):
        """§2 -- sheets carry more than one schedule, and merging them would
        interleave two unrelated tables."""
        first = grid_drawing(rows=4, columns=3, cell_text=True)
        second = grid_drawing(rows=4, columns=3, cell_text=True)
        shifted_geometry = [
            CadGeometry(
                entity_id=f"B{g.entity_id}",
                entity_type=g.entity_type,
                layer=g.layer,
                layout_index=0,
                points=tuple((x + 200.0, y) for x, y in g.points),
            )
            for g in second.geometry
        ]
        shifted_texts = [text(t.text, t.bbox.x0 + 200.0, t.bbox.y0) for t in second.texts if t.bbox]
        first.geometry = [*first.geometry, *shifted_geometry]
        first.texts = [*first.texts, *shifted_texts]

        assert len(detect_schedules(first).schedules) == 2

    def test_a_rotated_table_is_refused_rather_than_mangled(self):
        """§7 -- rotation is not supported, and the honest outcome is nothing.
        A rotated grid read as axis-aligned would produce cells that slice
        across several real ones."""
        import math

        cad = grid_drawing(rows=4, columns=3, cell_text=True)
        angle = math.radians(30)
        cos, sin = math.cos(angle), math.sin(angle)
        cad.geometry = [
            CadGeometry(
                entity_id=g.entity_id,
                entity_type=g.entity_type,
                layer=g.layer,
                layout_index=0,
                points=tuple((x * cos - y * sin, x * sin + y * cos) for x, y in g.points),
            )
            for g in cad.geometry
        ]
        assert detect_schedules(cad).schedules == []


class TestChunkRepresentation:
    """§10 -- a row has to survive being retrieved on its own."""

    def test_a_row_sentence_names_its_columns(self, schedule):
        sentences = schedule_row_sentences(schedule, "SSD11")
        bp1 = next(s for s in sentences if "BP-1" in s)
        assert "MEMBER SCHEDULE" in bp1
        assert "MARK BP-1" in bp1
        assert "QTY 1" in bp1
        assert "DESCRIPTION ASTM A36 25MM THK MS PLATE" in bp1

    def test_a_row_sentence_carries_the_drawing(self, schedule):
        assert "drawing SSD11" in schedule_row_sentences(schedule, "SSD11")[0]

    def test_one_sentence_per_data_row(self, schedule):
        assert len(schedule_row_sentences(schedule)) == 4

    def test_the_markdown_keeps_the_header_separator(self, schedule):
        markdown = schedule_markdown(schedule)
        assert markdown.splitlines()[1].startswith("| ---")
        assert "| BP-1 |" in markdown


class TestLoaderIntegration:
    """§9 -- the same pipeline, not a separate one."""

    @pytest.fixture(scope="class")
    def raw(self):
        return asyncio.run(DxfLoader().load(SCHEDULE))

    def test_each_row_becomes_its_own_block(self, raw):
        rows = [
            b for b in raw.text_blocks if b.element_label == "cad_schedule" and " - MARK " in b.text
        ]
        assert len(rows) == 4

    def test_a_row_block_carries_its_own_region(self, raw):
        """§12 -- so a citation can highlight the row rather than the table."""
        row = next(b for b in raw.text_blocks if "BP-1" in b.text)
        assert row.bbox is not None
        assert row.bbox.space == "sheet"
        assert 0.0 <= row.bbox.y0 < row.bbox.y1 <= 1.0

    def test_row_regions_do_not_all_coincide(self, raw):
        """Every row sharing one rectangle would mean the row band was never
        computed."""
        rows = [b for b in raw.text_blocks if " - MARK " in b.text and b.bbox]
        assert len({(round(b.bbox.y0, 4), round(b.bbox.y1, 4)) for b in rows}) == 4

    def test_the_structured_table_survives_as_well(self, raw):
        table = next(t for t in raw.tables if "MEMBER SCHEDULE" in (t.caption or ""))
        assert "| MARK |" in table.markdown
        assert "| BP-1 |" in table.markdown

    def test_schedule_blocks_name_their_layer(self, raw):
        row = next(b for b in raw.text_blocks if "BP-1" in b.text)
        assert row.layers == ["S-SCHEDULE"]

    def test_the_real_detail_sheet_gains_no_schedule_blocks(self):
        raw = asyncio.run(DxfLoader().load(DETAIL))
        assert [b for b in raw.text_blocks if b.element_label == "cad_schedule"] == []
